### ISSUE TITLE
[bug] Le bouton est sur "Dark" alors que le thème est clair

### ISSUE THREAD

**Issue by Herondil** [Raze91/Virtual_Keyboard#5]
Si j'active le mode "Dark" et que je réactualise la page, elle est claire alors que le bouton est sur "Light".

**Comment by Raze91** [comment]
Je n'ai pas bien compris le problème, lorsque le mode Dark est activé et que je réactualise la page, cette dernière redevient bien Light et le switch fonctionne également.

**Comment by Herondil** [comment]
C'est peut-être à cause du navigateur, je suis sur Firefox 82.0.3 !

**Comment by Raze91** [comment]
Corrigé !

**Comment by Herondil** [comment]
Le bug est de retour !

**Comment by Raze91** [comment]
Corrigé !
